application: open-booking-system
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /create/.*
  script: webapp.app
  login: required
- url: /static
  static_dir: static
- url: /.*
  script: webapp.app

# [END handlers]